// <auto-generated />
using System;
using Logic_Core_Server.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Logic_Core_Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Logic_Core_Server.Data.Entities.CalculationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("InputA")
                        .HasColumnType("float");

                    b.Property<double>("InputB")
                        .HasColumnType("float");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Result")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CalculationLogs");
                });

            modelBuilder.Entity("Logic_Core_Server.Data.Entities.OperationType", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Operations");

                    b.HasData(
                        new
                        {
                            Key = "add",
                            Formula = "arg1 + arg2",
                            IsActive = true,
                            Name = "חיבור",
                            Symbol = "+"
                        },
                        new
                        {
                            Key = "sub",
                            Formula = "arg1 - arg2",
                            IsActive = true,
                            Name = "חיסור",
                            Symbol = "-"
                        },
                        new
                        {
                            Key = "mul",
                            Formula = "arg1 * arg2",
                            IsActive = true,
                            Name = "כפל",
                            Symbol = "*"
                        },
                        new
                        {
                            Key = "div",
                            Formula = "arg1 / arg2",
                            IsActive = true,
                            Name = "חילוק",
                            Symbol = "/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
